config/routes.rb
require 'api_constraints'

Foreman::Application.routes.draw do
  #ENC requests goes here
  match "node/:name" => 'hosts#externalNodes', :constraints => { :name => /[^\.][\w\.-]+/ }
  post "reports/create"
  post "fact_values/create"

  resources :reports, :only => [:index, :show, :destroy, :create] do
    collection do
      get 'auto_complete_search'
    end
  end

  match '(:controller)/help', :action => 'welcome', :as => "help"
  constraints(:id => /[^\/]+/) do
    resources :hosts do
      member do
        get 'clone'
        get 'storeconfig_klasses'
        get 'externalNodes'
        get 'setBuild'
        get 'cancelBuild'
        get 'puppetrun'
        get 'pxe_config'
        put 'toggle_manage'
        post 'environment_selected'
        put 'power'
        get 'console'
        get 'bmc'
        put 'ipmi_boot'
      end
      collection do
        get 'multiple_actions'
        get 'multiple_parameters'
        post 'update_multiple_parameters'
        get 'select_multiple_hostgroup'
        post 'update_multiple_hostgroup'
        get 'select_multiple_environment'
        post 'update_multiple_environment'
        get 'multiple_puppetrun'
        post 'update_multiple_puppetrun'
        get 'multiple_destroy'
        post 'submit_multiple_destroy'
        get 'multiple_build'
        post 'submit_multiple_build'
        get 'reset_multiple'
        get 'multiple_disable'
        post 'submit_multiple_disable'
        get 'multiple_enable'
        post 'submit_multiple_enable'
        get 'auto_complete_search'
        get 'template_used'
        get 'active'
        get 'pending'
        get 'out_of_sync'
        get 'errors'
        get 'disabled'
        post 'current_parameters'
        post 'puppetclass_parameters'
        post 'process_hostgroup'
        post 'process_taxonomy'
        post 'hostgroup_or_environment_selected'
        post 'architecture_selected'
        post 'os_selected'
        post 'domain_selected'
        post 'use_image_selected'
        post 'compute_resource_selected'
        post 'medium_selected'
        get  'select_multiple_organization'
        post 'update_multiple_organization'
        get  'select_multiple_location'
        post 'update_multiple_location'
      end

      constraints(:host_id => /[^\/]+/) do
        resources :reports       ,:only => [:index, :show]
        resources :audits        ,:only => :index
        resources :facts         ,:only => :index, :controller => :fact_values
        resources :puppetclasses ,:only => :index
        resources :lookup_keys   ,:only => :show
      end
    end


    resources :bookmarks, :except => [:show]
    resources :lookup_keys, :except => [:new, :create] do
      resources :lookup_values, :only => [:index, :create, :update, :destroy]
      collection do
        get 'auto_complete_search'
      end
    end

    resources :facts, :only => [:index, :show] do
      constraints(:id => /[^\/]+/) do
        resources :values, :only => :index, :controller => :fact_values, :as => "host_fact_values"
      end
    end

  end

  resources :settings, :only => [:index, :update] do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :common_parameters do
    collection do
      get 'auto_complete_search'
    end
  end
  resources :environments do
    collection do
      get 'import_environments'
      post 'obsolete_and_new'
      get 'auto_complete_search'
    end
  end
  resources :trends do
    collection do
      post 'count'
    end
  end

  resources :hostgroups do
    member do
      get 'nest'
      get 'clone'
    end
    collection do
      get 'auto_complete_search'
      post 'environment_selected'
      post 'architecture_selected'
      post 'os_selected'
      post 'domain_selected'
      post 'use_image_selected'
      post 'medium_selected'
    end
  end

  resources :puppetclasses do
    collection do
      get 'import_environments'
      post 'obsolete_and_new'
      get 'auto_complete_search'
    end
    member do
      post 'parameters'
    end
    constraints(:id => /[^\/]+/) do
      resources :hosts
      resources :lookup_keys, :except => [:show, :new, :create]
    end
  end


  resources :smart_proxies, :except => [:show] do
    member do
      post 'ping'
    end
    constraints(:id => /[^\/]+/) do
      resources :puppetca, :only => [:index, :update, :destroy]
      resources :autosign, :only => [:index, :new, :create, :destroy]
    end
  end

  resources :fact_values, :only => [:index] do
    collection do
      get 'auto_complete_search'
    end
  end

  resources :notices, :only => :destroy
  resources :audits do
    collection do
      get 'auto_complete_search'
    end
  end

  if SETTINGS[:login]
    resources :usergroups
    resources :users, :except => [:show] do
      collection do
        get 'login'
        post 'login'
        get 'logout'
        get 'auth_source_selected'
        get 'auto_complete_search'
      end
    end
    resources :roles do
      collection do
        get 'report'
        post 'report'
        get 'auto_complete_search'
      end
    end

    resources :auth_source_ldaps
  end

  if SETTINGS[:unattended]
    resources :config_templates do
      collection do
        get 'auto_complete_search'
        get 'build_pxe_default'
        get 'revision'
      end
    end
    constraints(:id => /[^\/]+/) do
      resources :domains do
        collection do
          get 'auto_complete_search'
        end
      end
    end

    resources :operatingsystems do
      member do
        get 'bootfiles'
      end
      collection do
        get 'auto_complete_search'
      end
    end
    resources :media do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :models do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :architectures do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :ptables do
      collection do
        get 'auto_complete_search'
      end
    end

    constraints(:id => /[^\/]+/) do
      resources :compute_resources do
        member do
          post 'hardware_profile_selected'
          post 'cluster_selected'
          post 'ping'
        end
        constraints(:id => /[^\/]+/) do
          resources :vms, :controller => "compute_resources_vms" do
            member do
              put 'power'
              get 'console'
            end
          end
        end
        collection do
          get  'auto_complete_search'
          get 'provider_selected'
          put  'test_connection'
        end
        resources :images
      end
    end

    resources :subnets, :except => [:show] do
      collection do
        get 'auto_complete_search'
        get 'import'
        post 'create_multiple'
        post 'freeip'
      end
    end

    match 'unattended/template/:id/:hostgroup', :to => "unattended#template"
  end

  root :to => 'dashboard#index'
  match 'dashboard', :to => 'dashboard#index', :as => "dashboard"
  match 'dashboard/auto_complete_search', :to => 'hosts#auto_complete_search', :as => "auto_complete_search_dashboards"
  match 'statistics', :to => 'statistics#index', :as => "statistics"
  match 'status', :to => 'home#status', :as => "status"

  # match for all unattended scripts
  match 'unattended/(:action/(:id(.format)))', :controller => 'unattended'

  resources :tasks, :only => [:show]

  if SETTINGS[:locations_enabled]
    resources :locations do
      resources :hosts, :only => :index
      member do
        get 'select'
        match "clone" => 'locations#clone_taxonomy'
        post 'import_mismatches'
        get 'step2'
        get 'assign_hosts'
        post 'assign_all_hosts'
        put 'assign_selected_hosts'
      end
      collection do
        get 'auto_complete_search'
        get 'clear'
        get  'mismatches'
        post 'import_mismatches'
      end
    end
  end

  if SETTINGS[:organizations_enabled]
    resources :organizations do
      member do
        get 'select'
        match "clone" => 'organizations#clone_taxonomy'
        post 'import_mismatches'
        get 'step2'
        get 'assign_hosts'
        post 'assign_all_hosts'
        put 'assign_selected_hosts'
      end
      collection do
        get 'auto_complete_search'
        get 'clear'
        get  'mismatches'
        post 'import_mismatches'
      end
    end
  end

  resources :about, :only => :index do
  end

end

app/controllers/api/v1/compute_resources_controller.rb
module Api
  module V1
    class ComputeResourcesController < V1::BaseController
      before_filter :find_resource, :only => [:show, :update, :destroy]

      api :GET, "/compute_resources/", "List all compute resources."
      param :search, String, :desc => "filter results"
      param :order, String, :desc => "sort results"
      param :page, String, :desc => "paginate results"
      param :per_page, String, :desc => "number of entries per request"

      def index
        @compute_resources = ComputeResource.my_compute_resources.search_for(*search_options).paginate(paginate_options)
      end

      api :GET, "/compute_resources/:id/", "Show an compute resource."
      param :id, :identifier, :required => true

      def show
      end


      api :POST, "/compute_resources/", "Create a compute resource."
      param :compute_resource, Hash, :required => true do
        param :name, String
        param :provider, String, :desc => "Providers include #{ComputeResource::PROVIDERS.join(', ')}"
        param :url, String, :required => true, :desc => "URL for Libvirt, Ovirt, and Openstack"
        param :description, String
        param :user, String, :desc => "Username for Ovirt, EC2, Vmware, Openstack. Access Key for EC2."
        param :password, String, :desc => "Password for Ovirt, EC2, Vmware, Openstack. Secret key for EC2"
        param :uuid, String, :desc => "for Ovirt, Vmware Datacenter"
        param :region, String, :desc => "for EC2 only"
        param :tenant, String, :desc => "for Openstack only"
        param :server, String, :desc => "for Vmware"
      end

      def create
          @compute_resource = ComputeResource.new_provider(params[:compute_resource])
          process_response @compute_resource.save
      end


      api :PUT, "/compute_resources/:id/", "Update a compute resource."
      param :id, String, :required => true
      param :compute_resource, Hash, :required => true do
        param :name, String
        param :provider, String, :desc => "Providers include #{ComputeResource::PROVIDERS.join(', ')}"
        param :url, String, :desc => "URL for Libvirt, Ovirt, and Openstack"
        param :description, String
        param :user, String, :desc => "Username for Ovirt, EC2, Vmware, Openstack. Access Key for EC2."
        param :password, String, :desc => "Password for Ovirt, EC2, Vmware, Openstack. Secret key for EC2"
        param :uuid, String, :desc => "for Ovirt, Vmware Datacenter"
        param :region, String, :desc => "for EC2 only"
        param :tenant, String, :desc => "for Openstack only"
        param :server, String, :desc => "for Vmware"
      end

      def update
        process_response @compute_resource.update_attributes(params[:compute_resource])
      end

      api :DELETE, "/compute_resources/:id/", "Delete a compute resource."
      param :id, :identifier, :required => true

      def destroy
        process_response @compute_resource.destroy
      end

    end
  end
end

app/controllers/api/v2/compute_resources_controller.rb
module Api
  module V2
    class ComputeResourcesController < V1::ComputeResourcesController

      include Api::Version2
      include Api::TaxonomyScope

      def index
        super
        render :template => "api/v1/compute_resources/index"
      end

      def show
        super
        render :template => "api/v1/compute_resources/show"
      end

    end
  end
end

app/controllers/compute_resources_controller.rb
class ComputeResourcesController < ApplicationController
  include Foreman::Controller::AutoCompleteSearch
  AJAX_REQUESTS = %w{hardware_profile_selected cluster_selected}
  before_filter :ajax_request, :only => AJAX_REQUESTS
  before_filter :find_by_id, :only => [:show, :edit, :update, :destroy, :ping] + AJAX_REQUESTS

  def index
    begin
      values = ComputeResource.my_compute_resources.search_for(params[:search], :order => params[:order])
    rescue => e
      error e.to_s
      values = ComputeResource.my_compute_resources.search_for ""
    end

    respond_to do |format|
      format.html { @compute_resources = values.paginate :page => params[:page] }
      format.json { render :json => values }
    end
  end

  def new
    @compute_resource = ComputeResource.new
  end

  def show
    respond_to do |format|
      format.html
      format.json { render :json => @compute_resource }
    end
  end

  def create
    if params[:compute_resource].present? && params[:compute_resource][:provider].present?
      @compute_resource = ComputeResource.new_provider params[:compute_resource]
      if @compute_resource.save
        # Add the new compute resource to the user's filters
        @compute_resource.users << User.current
        process_success :success_redirect => @compute_resource
      else
        process_error
      end
    else
      @compute_resource = ComputeResource.new params[:compute_resource]
      @compute_resource.valid?
      process_error
    end
  end

  def edit
  end

  def update
    params[:compute_resource][:password] = @compute_resource.password if params[:compute_resource][:password].blank?
    if @compute_resource.update_attributes(params[:compute_resource])
      process_success
    else
      process_error
    end
  end

  def destroy
    if @compute_resource.destroy
      process_success
    else
      process_error
    end
  end

  #ajax methods
  def provider_selected
    @compute_resource = ComputeResource.new_provider :provider => params[:provider]
    render :partial => "compute_resources/form", :locals => { :compute_resource => @compute_resource }
  end

  def ping
    respond_to do |format|
      format.json {render :json => errors_hash(@compute_resource.ping)}
    end
  end

  def test_connection
    # cr_id is posted from AJAX function. cr_id is nil if new
    Rails.logger.info "CR_ID IS #{params[:cr_id]}"
    if params[:cr_id].present? && params[:cr_id] != 'null'
      @compute_resource = ComputeResource.find(params[:cr_id])
      params[:compute_resource].delete(:password) if params[:compute_resource][:password].blank?
      @compute_resource.attributes = params[:compute_resource]
    else
      @compute_resource = ComputeResource.new_provider(params[:compute_resource])
    end
    @compute_resource.test_connection
    render :partial => "compute_resources/form", :locals => { :compute_resource => @compute_resource }
  end

  def hardware_profile_selected
    compute = @compute_resource.hardware_profile(params[:hwp_id])
    compute.interfaces
    compute.volumes
    respond_to do |format|
      format.json { render :json => compute }
    end
  end

  def cluster_selected
    networks = @compute_resource.networks(:cluster_id => params[:cluster_id])
    respond_to do |format|
      format.json { render :json => networks }
    end
  end

  private

  def find_by_id
    @compute_resource = ComputeResource.find(params[:id])
    not_found and return unless @compute_resource
    deny_access and return unless ComputeResource.my_compute_resources.include?(@compute_resource)
  end
end

app/helpers/compute_resources_helper.rb
module ComputeResourcesHelper
  include LookupKeysHelper

  def show_console_action(state, link)
    state ? link : ""
  end

  def vm_state s
    s ? ' ' + _("Off") : ' ' + _("On")
  end

  def vm_power_class s
    "class='label #{s ? "label-success" : ""}'".html_safe
  end

  def vm_power_action vm
    opts = hash_for_power_compute_resource_vm_path(:compute_resource_id => @compute_resource, :id => vm.identity)
    html = vm.ready? ? { :confirm => _('Are you sure?'), :class => "btn btn-small btn-danger" } : { :class => "btn btn-small btn-info" }

    display_link_if_authorized (_("Power %s") % vm_state(vm.ready?)), opts, html.merge(:method => :put)
  end

  def memory_options max_memory
    gb = 1024*1024*1024
    opts = [0.25, 0.5, 0.75, 1, 2, 4, 8, 16]
    opts.map{|n| [number_to_human_size(n*gb), (n*gb).to_i] unless n > (max_memory / gb)}.compact
  end

  def password_placeholder(obj)
    obj.id ? "********" : ""
  end
end

app/views/compute_resources/_form.html.erb
<%= javascript "compute_resource" %>
<%= form_for @compute_resource, :html => {:data => {:id => @compute_resource.try(:id)}} do |f| %>
  <%= base_errors_for @compute_resource %>

  <% if show_taxonomy_tabs? %>
    <ul class="nav nav-tabs" data-tabs="tabs">
      <li class="active"><a href="#primary" data-toggle="tab"><%= _("Compute Resource") %></a></li>
      <% if show_location_tab? %>
        <li><a href="#locations" data-toggle="tab"><%= _("Locations") %></a></li>
      <% end %>
      <% if show_organization_tab? %>
        <li><a href="#organizations" data-toggle="tab"><%= _("Organizations") %></a></li>
      <% end %>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="primary">
  <% end %>
        <%= text_f f, :name %>
        <%= f.hidden_field(:provider, :id => '') if f.object.uuid.present? %>
        <%= selectable_f f, :provider, ComputeResource::PROVIDERS, { :include_blank => _("Choose a provider")},
                         {:label => _("Provider"), :disabled=> f.object.uuid.present?, :'data-url'=> provider_selected_compute_resources_path, :onchange => 'providerSelected(this);'} %>
        <%= textarea_f f, :description, :rows => 3 %>
        <div id='compute_connection'>
          <%= render "compute_resources/form/#{@compute_resource.provider.downcase}", :f => f unless @compute_resource.provider.empty? %>
        </div>
    <% if show_taxonomy_tabs? %>
      </div>
      <% if show_location_tab? %>
        <div class="tab-pane" id="locations">
          <%= multiple_checkboxes f, :locations, @compute_resource, Location, :label => _("Locations") %>
        </div>
      <% end %>

    <% if show_organization_tab? %>
        <div class="tab-pane" id="organizations">
          <%= multiple_checkboxes f, :organizations, @compute_resource, Organization, :label => _("Organizations") %>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= submit_or_cancel f %>
<% end %>

app/views/compute_resources/edit.html.erb
<% title _("Editing compute") %>

<%= render 'form' %>

app/views/compute_resources/index.html.erb
<% title _("Listing compute resources") %>
<% title_actions display_link_if_authorized(_("New Compute Resource"), hash_for_new_compute_resource_path), help_path %>

<table class="table table-bordered table-striped">
  <tr>
    <th><%= sort :name, :as => s_("ComputeResource|Name") %></th>
    <th><%= sort :type, :as => _("Type") %></th>
    <th></th>
  </tr>

<% @compute_resources.each do |compute| %>
  <tr>
    <td><%= link_to compute.name, compute %></td>
    <td><%= compute.provider_friendly_name %></td>
    <td>
      <%= action_buttons(link_to(_('Edit'), edit_compute_resource_path(compute)),
                         display_delete_if_authorized(hash_for_compute_resource_path(:id => compute), :confirm => _("Delete %s?") % compute.name)) %>
    </td>
  </tr>
<% end %>
</table>

<%= page_entries_info @compute_resources %>
<%= will_paginate @compute_resources %>

app/views/compute_resources/new.html.erb
<h1><%= _("New compute resource") %></h1>

<%= render 'form' %>

app/views/compute_resources/show.html.erb
<%= javascript "compute_resource" %>
<% title @compute_resource.name %>

<% title_actions link_to(_('Edit'), edit_compute_resource_path(@compute_resource), :class => "btn")  %>

<ul class="nav nav-tabs" data-tabs="tabs">
  <li class="active"><a href="#primary" data-toggle="tab"><%= _("Compute Resource") %></a></li>
  <li><a href="#vms" data-toggle="tab"><%= _("Virtual Machines") %></a></li>
  <% if @compute_resource.capabilities.include?(:image) -%>
    <li><a href="#images" data-toggle="tab"><%= _("Images") %></a></li>
  <% end -%>
</ul>

<div class="tab-content">

  <div class="tab-pane active" id="primary">
    <table class="table table-bordered table-striped">
      <th><%= _("Details") %></th>
      <th></th>

      <tr>
        <td><%= _("Provider") %></td>
        <td><%= @compute_resource.provider %></td>
      </tr>

      <tr>
        <td><%= _("Description") %></td>
        <td><%= @compute_resource.description %></td>
      </tr>

      <tr>
        <td><%= _("URL") %></td>
        <td><%= @compute_resource.url %></td>
      </tr>
    </table>
  </div>
  <div id="vms" class="tab-pane" data-url=<%= compute_resource_vms_path(@compute_resource) %>>
    <p id="spinner">
      <%= image_tag '/assets/spinner.gif' %>
      <%= _('Loading Virtual Machines information ...') %>
    </p>
  </div>
  <% if @compute_resource.capabilities.include?(:image) -%>
    <div id="images" class="tab-pane">
      <%= title_actions(display_link_if_authorized(_("New Image"), hash_for_new_compute_resource_image_path(:compute_resource_id => @compute_resource.id), :class => "btn btn-success")) %>
      <div id="images_list" data-url=<%= compute_resource_images_path(@compute_resource) %>>
        <p id="spinner">
          <%= image_tag '/assets/spinner.gif' %>
          <%= _('Loading Images information') %> ...
        </p>
      </div>
    </div>
  <% end -%>

</div>